version: "3.9"

services:

  backend:
    build: ./infra/php
    container_name: backend
    volumes:
      - ./backend:/backend

  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /work
    volumes:
      - ./frontend:/work
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  web:
    image: nginx:latest
    container_name: web
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    build: ./infra/mysql
    container_name: db
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=test
      - PMA_PASSWORD=12345678
    links:
      - db
    ports:
      - 8082:80
    depends_on:
      - db
    volumes:
      - /sessions

# 全てのサービス(コンテナ)が参照出来るトップレベルにボリュームを設定
volumes:
  #　名前付き永続化ボリュームなのでコンテナをstopしてもコンテナから紐づけられたデータを残る
  db-store:
